'use strict';
const $=i=>document.getElementById(i),N=i=>Number.parseFloat($(i).value),M=x=>Math.round(x).toLocaleString('ja-JP')+'万円';let accessToken='';
function pay(p,r,y){p=Math.max(0,p)*10000;const n=y*12,m=r/1200;if(!m)return p/n/10000;const f=(1+m)**n;return p*m*f/(f-1)/10000}
function bal(p,r,y,kY){p*=10000;const n=y*12,k=Math.min(n,Math.max(0,kY*12)),m=r/1200,a=pay(p/10000,r,y)*10000;if(k>=n)return 0;if(!m)return Math.max(0,p-a*k)/10000;const f=(1+m)**k;return Math.max(0,p*f-a*(f-1)/m)/10000}
function aiTitle(t){const h=$('summary')?.previousElementSibling;if(h)h.textContent=t}
function cleanSummary(t){return String(t||'').replace(/#{1,6}\s*/g,'').replace(/\*\*/g,'').replace(/\s+(総合結果|重要ポイント3点|10年間の家計|金利上昇|教育・大型支出|退職時住宅ローン|改善シナリオ|総括)\s*/g,'\n\n$1\n').trim()}
const ids=['age','retireAge','takehome','bonus','savings','living','car','otherDebt','education','retirementSave','price','down','acquisition','moving','rate','years','propertyTax','insurance','repairAnnual','eventYear','eventAmount','retirementLump','retirementLoanUse','educationPeakYear','educationPeakAmount'];
function vals(){return ids.reduce((o,k)=>(o[k]=N(k),o),{})}
function sim(v,price=v.price,rate=v.rate){const loan=Math.max(0,price-v.down),mp=pay(loan,rate,v.years),start=v.savings-v.down-v.acquisition-v.moving,reserve=Math.max(150,(v.living+v.car+v.otherDebt)*6);let cash=start,min=start,minYear=0;for(let y=1;y<=10;y++){cash+=v.takehome*12+v.bonus-(v.living+v.car+v.otherDebt+v.education+v.retirementSave)*12-(mp*12+v.propertyTax+v.insurance+v.repairAnnual)-(y===Math.round(v.eventYear)?v.eventAmount:0)-(v.educationPeakYear>0&&y===Math.round(v.educationPeakYear)?v.educationPeakAmount:0);if(cash<min){min=cash;minYear=y}}const rb=bal(loan,rate,v.years,Math.max(0,v.retireAge-v.age));return{loan,mp,start,reserve,end:cash,min,minYear,retireBal:rb,retireNetBal:Math.max(0,rb-v.retirementLoanUse)}}
async function render(v){const s=sim(v),st=sim(v,v.price,v.rate+1),ratio=s.mp/v.takehome*100,s300=sim(v,Math.max(1,v.price-300)),s500=sim(v,Math.max(1,v.price-500));let cls='good',title='🟢 安心できる範囲';if(s.start<0||s.min<0||ratio>30){cls='bad';title='🔴 負担が大きい可能性'}else if(s.start<s.reserve||s.min<s.reserve||ratio>25||st.mp-s.mp>=2||s.retireNetBal>0){cls='warn';title='🟡 注意が必要'}$('judgement').className='judgement '+cls;$('judgement').textContent=title;$('metrics').innerHTML=[['借入額',M(s.loan)],['月返済額',s.mp.toFixed(1)+'万円'],['購入直後の手元資金',M(s.start)],['生活防衛資金の目安',M(s.reserve)],['10年間の最低資金',M(s.min)+(s.minYear?'（'+s.minYear+'年後）':'（購入時）')],['10年後の資金',M(s.end)],['金利＋1.0%時',st.mp.toFixed(1)+'万円/月'],['退職時ローン残高',M(s.retireBal)],['退職金充当後の残債',M(s.retireNetBal)]].map(x=>'<div class="metric"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join('');
const risks=[];if(s.start<s.reserve)risks.push('購入直後の手元資金が生活防衛資金の目安 '+M(s.reserve)+'を下回ります。');if(s.min<0)risks.push((s.minYear?s.minYear+'年目':'購入時')+'に資金残高がマイナスとなる試算です。');if(ratio>25)risks.push('住宅ローン返済は手取り月収の'+ratio.toFixed(1)+'%です。');if(st.mp-s.mp>=2)risks.push('金利が1.0%上昇すると月返済が約'+(st.mp-s.mp).toFixed(1)+'万円増えます。');if(s.retireNetBal>0)risks.push('退職金充当後も約'+M(s.retireNetBal)+'の残債が残る試算です。');$('risks').innerHTML=(risks.length?risks:['現時点の入力条件では大きな警告項目は検出されませんでした。']).map(x=>'<div class="risk">・'+x+'</div>').join('');$('scenarios').innerHTML='<div class="scenario"><strong>購入価格を300万円下げる</strong><br>月返済 '+s300.mp.toFixed(1)+'万円／10年後資金 '+M(s300.end)+'</div><div class="scenario"><strong>購入価格を500万円下げる</strong><br>月返済 '+s500.mp.toFixed(1)+'万円／10年後資金 '+M(s500.end)+'</div>';
const fallback='現在の条件では「'+title.replace(/^..\s?/,'')+'」という試算です。\n\n購入直後の手元資金は'+M(s.start)+'、生活防衛資金の目安は'+M(s.reserve)+'です。購入後に現金が不足しやすい条件のため、価格・頭金・諸費用を慎重に見直す必要があります。\n\n10年間の最低資金残高は'+M(s.min)+(s.minYear?'（'+s.minYear+'年後）':'（購入時）')+'です。大型支出や教育費が重なると、家計の余裕がさらに小さくなる可能性があります。\n\n金利が1.0%上昇した場合、月返済は'+s.mp.toFixed(1)+'万円から'+st.mp.toFixed(1)+'万円になる試算です。金利上昇後も毎月の生活費を維持できるか確認してください。\n\n退職予定時点の住宅ローン残高は'+M(s.retireBal)+'、退職金充当後は'+M(s.retireNetBal)+'です。退職後の収入や年金額は未入力のため、老後全体の安全性は別途確認が必要です。';aiTitle('総合コメント');$('summary').textContent='総合コメントを作成しています…';$('result').style.display='block';
const payload={judgement:title,outputs:{loan:Math.round(s.loan),monthlyPayment:+s.mp.toFixed(2),purchaseCash:Math.round(s.start),reserveNeed:Math.round(s.reserve),minimumCash:Math.round(s.min),minimumCashYear:s.minYear,endCash10y:Math.round(s.end),stressPayment1pct:+st.mp.toFixed(2),retirementLoanBalance:Math.round(s.retireBal),retirementNetBalance:Math.round(s.retireNetBal)},riskMessages:risks,scenarios:{priceMinus300:{monthlyPayment:+s300.mp.toFixed(2),endCash10y:Math.round(s300.end)},priceMinus500:{monthlyPayment:+s500.mp.toFixed(2),endCash10y:Math.round(s500.end)}}};
try{const r=await fetch('/api/summary',{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+accessToken},body:JSON.stringify(payload)});if(!r.ok)throw new Error('summary_failed');const j=await r.json();if(!j.summary)throw new Error('summary_empty');aiTitle('AIによる総合分析');$('summary').textContent=cleanSummary(j.summary)}catch{aiTitle('総合コメント');$('summary').textContent=fallback}}
async function verify(){const sid=new URLSearchParams(location.search).get('session_id');if(!sid){$('gate').innerHTML='<h1>決済確認が必要です</h1><p>無料診断画面から決済を完了してください。</p>';return}try{const r=await fetch('/api/verify-session?session_id='+encodeURIComponent(sid)),j=await r.json();if(!r.ok||!j.paid)throw 0;accessToken=j.accessToken;$('gate').hidden=true;$('paidContent').hidden=false}catch{$('gate').innerHTML='<h1>決済を確認できませんでした</h1><p>決済完了後の画面からもう一度お試しください。</p>'}}
document.addEventListener('DOMContentLoaded',async()=>{await verify();$('form').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter||$('form').querySelector('button[type="submit"]'),old=btn?btn.textContent:'';const v=vals();if(ids.some(k=>!Number.isFinite(v[k]))){alert('入力内容を確認してください。');return}if(v.retireAge<=v.age||v.down>v.price||v.retirementLoanUse>v.retirementLump){alert('年齢・頭金・退職金の入力内容を確認してください。');return}if(btn){btn.disabled=true;btn.textContent='診断中です…'}try{await render(v)}finally{if(btn){btn.disabled=false;btn.textContent=old}}})});
